version: "3.9"

services:
  bot:
    build: .
    container_name: tg_bot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: telegram_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: tg_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  pgdata:
